- hosts: test
  become: true

  vars:
    password: pass
  tasks:
  - name: Create user
    user:
      name: ansible
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash
      groups: root
      append: yes
  - name: Создать SSH ключ для ansible в ~ansible/.ssh/id_rsa
    user:
      name: ansible
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
  - name: Добавить authorized key из файла id_rsa.pub
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name:  uncomment a line
    lineinfile: dest=/etc/ssh/sshd_config
                regexp='^PasswordAuthentication yes'
                insertafter='#PasswordAuthentication yes'
                line='PasswordAuthentication no'
                state=present
  - name: сreate directory
    file:
      path=/opt/test
      mode=0700
      owner=ansible
      group=ansible
      state=directory
