version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=localhost
        restart: always
        links:
          - "db:new_db"
          - "db:dev_db"


    db:
      image: mysql:latest
      container_name: mysql
      restart: always
      environment:
          - MYSQL_DATABASE=test
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=dev
          - MYSQL_PASSWORD=dev
      ports:
          - "8989:3306"
      volumes:
          - "./data/db/mysql:/var/lib/mysql"
networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28
